version: '3.9'
services:
  db:
    image: mysql:8.4
    container_name: lovable-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-lovable}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USER:-lovable}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-lovable}
      DB_USER: ${DB_USER:-lovable}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      FILE_STORAGE_PATH: /data/storage
    volumes:
      - app_storage:/data/storage
    ports:
      - "8080:8080"

volumes:
  db_data:
  app_storage:
