server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lovable}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file-storage:
  base-path: ${FILE_STORAGE_PATH:storage}

management:
  endpoints:
    web:
      exposure:
        include: health,info
